#!/bin/bash
#SBATCH --job-name=FDTD_2D
#SBATCH --partition=s_standard
#SBATCH --nodes=1
#SBATCH --ntasks=36
#SBATCH --cpus-per-task=1
#SBATCH --time=2:00:00
#SBATCH --mail-user=daniel.repp@uni-jena.de
#SBATCH --exclusive
#SBATCH --mem-per-cpu=4096
#SBATCH --mail-type=ALL


module purge
source /home/ni86did/.bashrc
module load compiler/intel/2020-Update2 
./fdtd2D